### ISSUE TITLE
Lab1的疑問

### ISSUE THREAD

**Issue by krscent** [2020-DL-Training-Program/Lab1-Backpropagation#3]
助教你好，請問 dim=[2, 3, 3, 1]，各別代表甚麼定義（或是甚麼東西 ? ）上的 2 3 3 1 呢?

**Comment by zivzone** [comment]
@krscent 你好，分別代表 input layer, hidden layer1, hidden layer2 以及 output layer 的 neuron 數。這邊雖沒設限 hidden layer 的 neuron 數，但各3個就很夠用了，但也可以試試其他數字並記錄以及比較。
