### ISSUE TITLE
Lab1提問

### ISSUE THREAD

**Issue by Jenny338** [2020-DL-Training-Program/Lab1-Backpropagation#4]
請問在training的時候，出現RuntimeWarning: overflow encountered in exp 和RuntimeWarning: overflow encountered in multiply
  return z*(1-z)的錯誤
可能是initial weight沒設好呢，或是說backpropagation沒寫好呢

**Comment by zivzone** [comment]
@Jenny338 你好，不確定你是因為何種原因導致這個問題因為沒看到你的 code 是怎麼寫的，但依你的敘述，我猜是 sigmoid 那邊爆炸了。
目前判斷 exp 裡面出事，因為 x 很大时，exp(x)可能會發生溢出。
可以在 sigmoid 那裏加一些判斷條件來處理
附上一個發生 overflow 的例子原因解釋:
https://stackoverflow.com/questions/24638059/runtimewarning-overflow-encountered-in-np-expx2
另外，如果是 initial weight 跟 backpropagation 之間去猜的話，因為 initial weight 基本上也就只是個 random 去創的(大家大概也都是這樣寫的)，所以問題應該不會在這，所以我猜是 backpropagation 那邊爆掉了。
但可以看一下跑 forward 時還沒跑第一次 backward 就爆了還是跑完 backward 之後才爆，這樣才能判斷問題在哪裡是不是 backward 那邊導致目前這個問題。

**Comment by Jenny338** [comment]
我找到問題了~~ 是inverse sigmoid那寫錯
謝謝助教
