### ISSUE TITLE
一次餵所有data

### ISSUE THREAD

**Issue by jasperchang504** [2020-DL-Training-Program/Lab1-Backpropagation#5]
因為XOR case收斂不了
助教我想請問我如果想要一次餵所有data
back-propagation應該怎麼控制維度

**Comment by zivzone** [comment]
@jasperchang504 如果是想使用 batch training 的話，可以參考
https://stats.stackexchange.com/questions/174708/how-are-weights-updated-in-the-batch-learning-method-in-neural-networks

**Comment by jasperchang504** [comment]
他的意思是在weight的ˊ地方沿著data數量平均掉嗎

**Comment by jasperchang504** [comment]
例如我們有20比data, Loss的微分應該是20筆還是還是1筆呢
Loss: 1/M * sum(.....)  --> 用sum會全部合在一起@@..

**Comment by zivzone** [comment]
loss 取 mean 之後做 backpropagation
