### ISSUE TITLE
問問題

### ISSUE THREAD

**Issue by krscent** [2020-DL-Training-Program/Lab1-Backpropagation#6]
助教你好，請問在推導back偏微分時，要怎麼判斷哪些時候使用kron、dot、multiply呢？

**Comment by zivzone** [comment]
在這一次lab 可以不用kron(這個其實有意點炫技的意味，所以可以不用太在意)，僅用 dot 、multiply 做出來這一次 lab，但若是有興趣 kron 怎麼做出來可以知後找助教討論。

**Comment by krscent** [comment]
助教你好，為什麼在使用 np.multiply 時，矩陣大小適合的情況下，會出現下列error呢?

ValueError: operands could not be broadcast together with shapes (1,4) (4,3)

**Comment by krscent** [comment]
助教你好，請問coding的時候，變數的命名，都必須要按照ｓｐｃｅ嗎？例如：Z1 必須要是𝒁𝟏 = 𝝈(𝑿𝑊1)，不能在ｃｏｄｉｎｇ的時候因為比較好記，命名為A1？

**Comment by zivzone** [comment]
@krscent 需要看一下你的 code 才比較好判斷問題在哪裏。變數名都可以變呀，只要不違反那個 spec pdf檔都可，那這一次的 spec 我印象中只有要求能夠成功訓練起來，中間變數名我印象中是不管的
