### ISSUE TITLE
Lab1的XOR Train不起來

### ISSUE THREAD

**Issue by andystrike** [2020-DL-Training-Program/Lab1-Backpropagation#7]
助教您好，Lab1的Linear可以正常運作，但切換到XOR就會卡住train不下去
請問XOR是僅需要調整Learning rate就可以train出來的嗎?
還是說有什麼地方遺漏了?

(我切換了0.001~0.9...都Train不出來Orz)

**Comment by YiLunLee** [comment]
XOR 確實會比 Linear 難 train，假設你的實驗沒問題的話 (目前看來Linear是可以運作)，可以再把 Learning rate往上調 (5或10之類的)，另外如果你是一次餵一個data的話也可以嘗試改成用batch的方式train。

**Comment by andystrike** [comment]
謝謝助教，我反覆看過幾次後
1. 發現code有寫錯，但沒想到寫錯的code在linear的狀況也可以train的起來...
2. 調整batch size讓我train起來了
3. learning rate小一點比較好train(走的步伐比較小)

**Comment by zivzone** [comment]
@andystrike 突然想到就算沒有 activation function，linear 好像也是練得起來的
